### ISSUE TITLE
About per-pixel features 

### ISSUE THREAD

**Issue by ousinkou** [tedchao/LoCoPalettes#1]
Hard to run code of Semantic Soft Segmentation. Their pretrained model link is also broken. Is there another way to get per-pixel features?

**Comment by tedchao** [comment]
Hi,

I have updated my forked repo from Aksoy's code. See [here](https://github.com/tedchao/SIGGRAPH18SSS).
I have tested the repo. It should be working now. Please do take a look.

Best,
Ted

**Comment by ousinkou** [comment]
Thank you. It's working now.

**Comment by PaiDii** [comment]
can u provide the pre-trained model of getting per-pixel features? The new link he provided is invalid
