### ISSUE TITLE
May I ask if you can provide the pre-trained model in Aksoy's code? The new link he provided is invalid

### ISSUE THREAD

**Issue by PaiDii** [tedchao/LoCoPalettes#3]
May I ask if you can provide the pre-trained model in Aksoy's code? The new link he provided is invalid

**Comment by tedchao** [comment]
Hi,

Thanks for letting me know.
Model link is updated. See [here](https://github.com/tedchao/SIGGRAPH18SSS).

Ted

**Comment by PaiDii** [comment]
ok! Thank u
